In [1]:
import numpy as np
import pandas as pd
dogs = pd.read_csv('C:/Users/nswat/Documents/DataCamp/Datasets/PersonalDatasets/dogs.csv')

dogs_ind3 = dogs.set_index(['breed', 'color'])

dogs_ind3.sort_index(level=['color', 'breed'], ascending=[True, False])

                      name  height_cm  weight_kg date_of_birth
breed       color
Poodle      Black  Charlie         43         24    2016-09-16
Labrador    Black      Max         59         29    2017-01-20
            Brown    Bella         56         24    2013-07-01
Chow Chow   Brown     Lucy         46         24    2014-08-25
Schnauzer   Gray    Cooper         49         17    2011-12-11
Chihuahua   Tan     Stella         18          2    2015-04-20
St. Bernard White   Bernie         77         74    2018-02-27