In [1]:
import pandas as pd
grants = pd.read_csv('C:/Users/nswat/Documents/DataCamp/Datasets/4JoiningDataWPandasDatasets/Small_Business_Grant_Agreements.csv')
licenses = pd.read_csv('C:/Users/nswat/Documents/DataCamp/Datasets/4JoiningDataWPandasDatasets/licenses.csv')

grants.merge(licenses, on=['address', 'zip'])

,address,zip,grant,company,account,ward,aid,business
0,2105 S STATE ST,60616.0,743,REGGIE'S BAR & GRILL,307071,3,743,REGGIE'S BAR & GRILL
1,13200 S HOUSTON AVE,60633.0,829,HONEYBEERS,10,10,829,HONEYBEERS
2,5089 S ARCHER AVE,60632.0,775,CELINA DELI,10002,14,775,CELINA DELI
3,2005 W 43RD ST,60609.0,NaN,KRAFT FOODS NORTH AMERICA,10005,12,NaN,KRAFT FOODS NORTH AMERICA
4,3651 N SOUTHPORT AVE,60613.0,638,NEYBOUR'S TAVERN & GRILLE,10044,44,638,NEYBOUR'S TAVERN & GRILLE
...,...,...,...,...,...,...,...,...
10869,2717 E 95TH ST,60617.0,NaN,J M V CORP,8634,10,NaN,J M V CORP
10870,103 N WELLS ST 1ST,60606.0,708,AMERICASH LOANS LLC,86350,42,708,AMERICASH LOANS LLC
10871,6720 W ARCHER AVE 1,60638.0,775,MC DONALD'S,86352,23,775,MC DONALD'S
10872,951 W ARMITAGE AVE 1,60614.0,638,VOSGES HAUT-CHOCOLAT,86355,43,638,VOSGES HAUT-CHOCOLAT
10873,5400-5404 S HALSTED ST 1ST,60609.0,775,ALMUFLIHI FOOD & LIQUOR,86373,20,775,ALMUFLIHI FOOD & LIQUOR